apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minetest.fullname" . }}-config
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
